services:
  api:
    build: .
    container_name: TSM
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    restart: unless-stopped